name: Version Bump
description: 'Bump the version and create a new tag'

inputs:
  version_type:
    description: 'The type of version bump (major, minor, patch)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Git
      shell: bash
      run: |
        sudo yum install -y git
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git config --global --add safe.directory /github/workspace

        ls -l

    - name: Fetch Tags
      shell: bash
      run: |
        git fetch --tags

    - name: Calculate New Version
      shell: bash
      run: |
        latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
        version=$(echo $latest_tag | sed 's/^v//')
        major=$(echo $version | cut -d. -f1)
        minor=$(echo $version | cut -d. -f2)
        patch=$(echo $version | cut -d. -f3)
        if [[ "${{ inputs.version_type }}" == "major" ]]; then
          new_version="$((major + 1)).0.0"
        elif [[ "${{ inputs.version_type }}" == "minor" ]]; then
          new_version="$major.$((minor + 1)).0"
        else
          new_version="$major.$minor.$((patch + 1))"
        fi
        echo "New version: $new_version"
        echo "new_version=v$new_version" >> $GITHUB_ENV

    - name: Create New Tag
      shell: bash
      run: |
        git tag $new_version
        git push origin $new_version
