name: CI Workflow
run-name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci-pipeline:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python 3.12
        run: |
          sudo yum update -y
          sudo yum install python3 -y
          sudo yum install -y python3-pip

      - name: Install Docker
        run: |
          sudo yum install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER
          newgrp docker
          sudo chmod 666 /var/run/docker.sock
          docker --version

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest requests mysql-connector-python

      - name: Run Unit Tests
        run: pytest db_app/test_users.py

      - name: Trivy Code Security Scan
        uses: ./.github/actions/security-scan
        with:
          scan_type: 'repository'
          severities: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL' # 'HIGH,CRITICAL'

      - name: Build Docker Image
        run: |
          sudo docker build -t python-app ./db_app
          sudo docker images

      - name: Trivy Docker Security Scan
        uses: ./.github/actions/security-scan
        with:
          scan_type: 'image'
          image_to_scan: 'python-app:latest'
          severities: 'HIGH,CRITICAL'

      - name: Run Integration Tests
        uses: ./.github/actions/integration
        with:
          skip_checkout: 'true'

      - name: Bump Version
        uses: ./.github/actions/version-bump
        with:
          version_type: 'patch'
